Repository webtoon/psd, pull requests merged in 2022-10, with the labels that each got.

#58 fix: left sidebar width in wider screen
  packages/example-browser/src/style.css
Labels: type: enhancement

#60 build: properly enable source map
  packages/decoder/vite.config.ts
  packages/psd/vite.config.ts
Labels: type: maintenance

#63 bugfix: introduce optional padding in TaggedBlocks
  packages/psd/src/sections/LayerAndMaskInformation/AdditionalLayerInfo/index.ts
  packages/psd/src/sections/LayerAndMaskInformation/readLayerRecordsAndChannels.ts
Labels: type: bug
